### ISSUE TITLE
Issue with the docker compose sample in the Readme file.

### ISSUE THREAD

**Issue by Caelestis94** [wow-signal-dev/metadata-remote#12]
Super simple fix, the docker compose sample provided in the `Installation` section didn't work for me, couldn't pull the image down, gave me this error : `pull access denied for wowsignaldev/metadata-remote, repository does not exist or may require 'docker login': denied`

```yaml
version: '3.8'
services:
  metadata-remote:
    image: wowsignaldev/metadata-remote:latest <-- ❌  issue is here  
    container_name: metadata-remote
    ports:
      - "8338:8338"
    volumes:
      - /your/music/directory:/music
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
```
just needed to swap it out with this line 

```
ghcr.io/wow-signal-dev/metadata-remote:latest
```
